name: RecipeMaker
version: '${version}'
main: org.recipemaker.RecipeMaker
api-version: '1.20'
libraries:
  - "net.kyori:adventure-platform-bukkit:4.3.2"
  - "net.kyori:adventure-api:4.15.0"
commands:
  rm:
    description: 'Your command description'
    usage: '/rm <subcommand>'
